openapi: "3.1.0"
info:
  title: "auth_app API"
  description: "auth_app API"
  version: "1.0.0"
servers:
  - url: "http://localhost:8080/"
paths:
  /api/v1/auth/login:
    get:
      summary: "GET api/v1/auth/login"
      operationId: "login"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginDto"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "string"
  /api/v1/auth/remember-me/{username}:
    post:
      summary: "POST api/v1/auth/remember-me/{username}"
      operationId: "rememberMe"
      parameters:
        - name: "username"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
  /api/v1/auth/refresh/{username}:
    get:
      summary: "GET api/v1/auth/refresh/{username}"
      operationId: "generateRefreshToken"
      parameters:
        - name: "username"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
  /api/v1/auth/logout:
    delete:
      summary: "DELETE api/v1/auth/logout"
      operationId: "logout"
      responses:
        "200":
          description: "OK"
components:
  schemas:
    LoginDto:
      type: "object"
      properties:
        username:
          type: "string"
          maxLength: 16
        password:
          type: "string"
          maxLength: 16