openapi: 3.0.3
info:
  title: Guest Controller API
  description: Guest access operations for anonymous users.
  version: "1.0.0"
  contact:
    name: Immortals Team

servers:
  - url: /api/v1/users
    description: Guest API server

paths:
  /guest-login:
    get:
      summary: Guest Login
      operationId: loginWithGuestCredentials
      description: Generates a guest token for anonymous access without requiring credentials.
      tags: [ Guest ]
      responses:
        '200':
          description: Guest token generated successfully.
          headers:
            Authorization:
              description: JWT guest token with Bearer prefix.
              schema:
                type: string
                example: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
          content:
            application/json:
              schema:
                type: string
                example: "Guest Token generate successfully"
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  schemas:
    ApiErrorResponse:
      type: object
      properties:
        httpStatus:
          type: string
          description: HTTP status code as a string
        timeStamp:
          type: string
          format: date-time
        moreInfo:
          type: string
        errorCode:
          type: integer
        errorMessage:
          type: string
        errors:
          type: array
          items:
            type: string

  responses:
    InternalServerError:
      description: Internal server error.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiErrorResponse'

tags:
  - name: Guest
    description: Guest access operations