openapi: "3.1.0"
info:
  title: "auth_app API"
  description: "auth_app API"
  version: "1.0.0"
servers:
  - url: "https://auth_app"
paths:
  /api/v1/users/guest-login:
    get:
      summary: "GET api/v1/users/guest-login"
      operationId: "loginWithGuestCredentials"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "string"